[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
HadronicLineshapes = "49c9d978-1f9d-4e96-a984-0a9783c0b9bf"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Documenter = "1"
